In [12]:
from __future__ import print_function
from time import time

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.datasets import fetch_20newsgroups
import pandas as pd
import numpy as np

from tensor_lda.tensor_lda import TensorLDA

import scipy
import scipy.sparse as sparse
from sklearn.preprocessing import normalize 
import pickle

In [2]:
# import dataset
file_path = "../DATA/GSE131928_RAW/GSM3828672_Smartseq2_GBM_IDHwt_processed_TPM.tsv"
df = pd.read_csv(file_path, sep='\t').transpose()

# extract gene names and expression values
gene_names = df.values[0]
exp_cell_normalized = np.round(normalize(df.values[1:],axis=0,norm='max')*100)

In [4]:
var = exp_cell_normalized.var(axis = 0)

n_genes = 1500

num_topics = [4,5,7,8]

ind = np.argpartition(var, -n_genes)[-n_genes:]
tf = sparse.csr_matrix(exp_cell_normalized[:,ind].astype(float))
tf_feature_names = gene_names[ind]

predictions = []

for n_components in num_topics:
    lda = TensorLDA(n_components=n_components, alpha0=.01)
    lda.fit(tf)
    prediction = lda.transform(tf).argmax(axis=1)
    predictions.append([lda, prediction])
    

In [16]:
with open("results/topic4578gene1500.pkl", 'wb') as f:
    pickle.dump(predictions, f,-1)


In [17]:
elements_count = {}
for element in predictions[0][1]:
       # checking whether it is in the dict or not
       if element in elements_count:
          # incerementing the count by 1
          elements_count[element] += 1
       else:
          # setting the count to 1
          elements_count[element] = 1
elements_count


{0: 884, 2: 2777, 3: 2232, 1: 2037}

In [18]:
elements_count = {}
for element in predictions[1][1]:
       # checking whether it is in the dict or not
       if element in elements_count:
          # incerementing the count by 1
          elements_count[element] += 1
       else:
          # setting the count to 1
          elements_count[element] = 1
elements_count


{0: 868, 3: 2583, 4: 2136, 2: 1991, 1: 352}

In [26]:
with open("results/filtered_gene1500_topic6.pkl", 'rb') as f:  # Python 3: open(..., 'wb')
    [topic6_tf,topic6_tf_feature_names, topic6_lda, topic6_prediction]=pickle.load(f)

elements_count = {}
for element in topic6_prediction:
       # checking whether it is in the dict or not
       if element in elements_count:
          # incerementing the count by 1
          elements_count[element] += 1
       else:
          # setting the count to 1
          elements_count[element] = 1
elements_count

{1: 847, 2: 2233, 5: 1907, 3: 819, 4: 1877, 0: 247}

In [19]:
elements_count = {}
for element in predictions[2][1]:
       # checking whether it is in the dict or not
       if element in elements_count:
          # incerementing the count by 1
          elements_count[element] += 1
       else:
          # setting the count to 1
          elements_count[element] = 1
elements_count


{1: 845, 2: 507, 4: 1815, 6: 1841, 3: 553, 5: 2108, 0: 261}

In [25]:
elements_count = {}
for element in predictions[3][1]:
       # checking whether it is in the dict or not
       if element in elements_count:
          # incerementing the count by 1
          elements_count[element] += 1
       else:
          # setting the count to 1
          elements_count[element] = 1
elements_count


{1: 847, 4: 1644, 6: 1797, 5: 856, 3: 1384, 2: 203, 7: 961, 0: 238}

In [27]:
num_topics = [9,10]

for n_components in num_topics:
    lda = TensorLDA(n_components=n_components, alpha0=.01)
    lda.fit(tf)
    prediction = lda.transform(tf).argmax(axis=1)
    predictions.append([lda, prediction])
    

In [33]:
elements_count = {}
for element in predictions[4][1]:
       # checking whether it is in the dict or not
       if element in elements_count:
          # incerementing the count by 1
          elements_count[element] += 1
       else:
          # setting the count to 1
          elements_count[element] = 1
elements_count


{0: 824, 6: 896, 7: 1127, 8: 1734, 2: 250, 3: 294, 4: 1128, 5: 1447, 1: 230}

In [34]:
elements_count = {}
for element in predictions[5][1]:
       # checking whether it is in the dict or not
       if element in elements_count:
          # incerementing the count by 1
          elements_count[element] += 1
       else:
          # setting the count to 1
          elements_count[element] = 1
elements_count


{1: 771,
 8: 1274,
 9: 1244,
 6: 937,
 4: 946,
 3: 507,
 5: 403,
 7: 1498,
 2: 109,
 0: 241}

In [ ]:
predictions.append()

In [35]:
lda = TensorLDA(n_components=3, alpha0=.01)
lda.fit(tf)
prediction = lda.transform(tf).argmax(axis=1)
predictions.append([lda, prediction])
    

In [36]:
elements_count = {}
for element in predictions[6][1]:
       # checking whether it is in the dict or not
       if element in elements_count:
          # incerementing the count by 1
          elements_count[element] += 1
       else:
          # setting the count to 1
          elements_count[element] = 1
elements_count


{0: 884, 1: 3486, 2: 3560}

In [37]:
predictions.append([topic6_lda, topic6_prediction])

In [41]:
idx_list = [6,0,1,7,2,3,4,5]
predictions1 = []
for idx in idx_list:
    predictions1.append(predictions[idx])

In [42]:
with open("results/topic345678910gene1500.pkl", 'wb') as f:
    pickle.dump(predictions1, f,-1)


In [ ]:
# Keep the top 2000 genes with the highest variance
var = exp_cell_normalized.var(axis = 0)
ind = np.argpartition(var, -1500)[-1500:]
tf = sparse.csr_matrix(exp_cell_normalized[:,ind].astype(float))
tf_feature_names = gene_names[ind]

In [ ]:
with open("filtered_1500_gene_dataset.pkl", 'wb') as f:
    pickle.dump([tf,tf_feature_names], f,-1)


In [ ]:
with open('filtered_1500_gene_dataset.pkl', 'rb') as f:  # Python 3: open(..., 'rb')
     [tf,tf_feature_names] = pickle.load(f)

In [ ]:
n_samples = tf.shape[0]
n_features = tf.shape[1]
n_components = 6
n_top_words = 30


In [ ]:
lda = TensorLDA(n_components=n_components, alpha0=.01)

In [ ]:
lda.fit(tf)

In [ ]:
prediction = lda.transform(tf).argmax(axis=1)

In [ ]:
with open("results/filtered_gene1500_topic6.pkl", 'wb') as f:  # Python 3: open(..., 'wb')
    pickle.dump([tf,tf_feature_names, lda, prediction], f,-1)


In [2]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        topic_prior = model.alpha_[topic_idx]
        message = "Topic #%d (prior: %.3f): " % (topic_idx, topic_prior)
        message += " ".join([feature_names[i]
                             for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)
    print()


# Load the 20 newsgroups dataset and vectorize it. We use a few heuristics
# to filter out useless terms early on: the posts are stripped of headers,
# footers and quoted replies, and common English words, words occurring in
# only one document or in at least 95% of the documents are removed.

print("Loading dataset...")
t0 = time()
dataset = fetch_20newsgroups(shuffle=True, random_state=2,
                             remove=('headers', 'footers', 'quotes'))
data_samples = dataset.data[:n_samples]
print("done in %0.3fs." % (time() - t0))

# Use tf (raw term count) features for LDA.
print("Extracting tf features for LDA...")
tf_vectorizer = CountVectorizer(max_df=0.8, min_df=5,
                                max_features=n_features,
                                stop_words='english')
t0 = time()
tf = tf_vectorizer.fit_transform(data_samples)
print("done in %0.3fs." % (time() - t0))
print()

print("Fitting TensorLDA models with tf features, "
      "n_samples=%d and n_features=%d..."
      % (n_samples, n_features))

lda = TensorLDA(n_components=n_components, alpha0=.1)

t0 = time()
lda.fit(tf)
print("done in %0.3fs." % (time() - t0))

print("\nTopics in LDA model:")
tf_feature_names = tf_vectorizer.get_feature_names()
print_top_words(lda, tf_feature_names, n_top_words)

doc_topics = lda.transform(tf[0:2, :])
print(doc_topics[0, :])
print(data_samples[0])

Loading dataset...


NameError: name 'n_samples' is not defined

In [ ]:
# with open('lda_model.pkl', 'rb') as f:  # Python 3: open(..., 'rb')
#      lda = pickle.load(f)


In [ ]:
# lda.transform(tf).argmax(axis=1))

In [ ]:
# # Specify the hyperparameters
# num_genes_list = [500,1000,1500]
# num_topics = [3,5,7,9,11]
# predictions = []
# # load the result for each pair of hyperparameters and do transformation
# for n_genes in num_genes_list:
#     with open("results/filtered_gene%d_exp.pkl"%(n_genes), 'rb') as f:  # Python 3: open(..., 'rb')
#         [tf,tf_feature_names] = pickle.load(f)
#     for n_components in num_topics:
#         with open("results/lda_model_topic%d_gene%d.pkl"%(n_components, n_genes), 'rb') as f:
#             lda = pickle.load(f)
#         predictions.append(lda.transform(tf).argmax(axis=1))


In [ ]:
# with open("results/predictions.pkl", 'wb') as f:
#     pickle.dump(predictions, f,-1)


In [ ]:
# with open("results/predictions.pkl", 'wb') as f:
#     predictions1 = pickle.load(f)


In [ ]:
# elements_count_collection = []
# for i in range(10, 15):
#     elements_count = {}
#     # iterating over the elements for frequency
#     for element in predictions[i]:
#        # checking whether it is in the dict or not
#        if element in elements_count:
#           # incerementing the count by 1
#           elements_count[element] += 1
#        else:
#           # setting the count to 1
#           elements_count[element] = 1
#     # printing the elements frequencies
#     elements_count_collection.append(elements_count)


In [ ]:
# elements_count_collection

In [ ]:
# for i in range(10,14):
#     print(i)

In [22]:
# with open("results/filtered_gene1500_topic6.pkl", 'rb') as f:  # Python 3: open(..., 'wb')
#     [topic6_tf,topic6_tf_feature_names, topic6_lda, topic6_prediction]=pickle.load(f)

# elements_count = {}
# for element in topic6_prediction:
#        # checking whether it is in the dict or not
#        if element in elements_count:
#           # incerementing the count by 1
#           elements_count[element] += 1
#        else:
#           # setting the count to 1
#           elements_count[element] = 1
# elements_count

{1: 847, 2: 2233, 5: 1907, 3: 819, 4: 1877, 0: 247}

In [ ]:
topic6_prediction

In [3]:
with open("results/filtered_gene1500_topic6.pkl", 'rb') as f:  # Python 3: open(..., 'wb')
    [topic6_tf,topic6_tf_feature_names, topic6_lda, topic6_prediction]=pickle.load(f)


In [6]:
print_top_words(topic6_lda, topic6_tf_feature_names, 20)

Topic #0 (prior: 0.000): GABARAPL2 GPM6B TMEM59 SERINC1 FEZ1 SOX2-OT TBCB CBR1 ARL6IP5 CD9 TALDO1 PMP22 PLEKHB1 ATP6V0B RNF13 LGALS3BP PRNP RNF130 GSN FIS1
Topic #1 (prior: 0.001): CD74 SAT1 HLA-E HLA-B HLA-C NPC2 ARPC3 ZFP36 RPL13A GRN JUNB HERPUD1 ASAH1 RPL21P28 SDCBP COTL1 CLIC1 ATP6V0E1 ID2 PPT1
Topic #2 (prior: 0.002): PTPRZ1 GPM6B PTN VIM CNN3 TUBB2B C1orf61 SLC1A3 GPM6A PCDHGC3 NGFRAP1 BCAN PON2 FABP7 GPR56 HEPN1 ATP6AP2 CD9 S100B CD99
Topic #3 (prior: 0.002): DNAJB6 LDHA BZW1 VIM SERINC1 RPL13A UBE2D3 CLK1 STRAP ARPC1A RPL21P28 MYL12B ATP6AP2 H2AFZ CCNI RAB1A EIF3F DDOST CAPZA2 ARPC3
Topic #4 (prior: 0.002): TUBB2B GPM6A MAP2 STMN1 FXYD6 PTPRZ1 GPR56 RBM4 DNAJB6 GPM6B MLLT11 TSC22D1 CLK1 TUBB3 ILF2 NGFRAP1 MARCKSL1 BZW1 C1orf61 DBN1
Topic #5 (prior: 0.003): NME1 TUBB2B NME2 CCT7 H2AFZ NGFRAP1 PSMB6 ILF2 GPM6B CCT3 ATP5C1 STMN1 HSBP1 PTN COX7A2 FXYD6 MDH2 UQCRH UQCRC1 BRK1



In [13]:
with open("results/topic345678910gene1500.pkl", 'rb') as f:
    predictions = pickle.load(f)

In [14]:
predictions

[[TensorLDA(alpha0=0.01, converge_tol=0.0001, inference_converge_tol=1e-06,
       inference_step_size=0.001, max_inference_iter=1000, max_iter=1000,
       n_components=3, n_restart=10, random_state=None, smooth_param=0.01,
       verbose=0),
  array([0, 0, 0, ..., 2, 1, 1], dtype=int64)],
 [TensorLDA(alpha0=0.01, converge_tol=0.0001, inference_converge_tol=1e-06,
       inference_step_size=0.001, max_inference_iter=1000, max_iter=1000,
       n_components=4, n_restart=10, random_state=None, smooth_param=0.01,
       verbose=0),
  array([0, 0, 0, ..., 3, 2, 2], dtype=int64)],
 [TensorLDA(alpha0=0.01, converge_tol=0.0001, inference_converge_tol=1e-06,
       inference_step_size=0.001, max_inference_iter=1000, max_iter=1000,
       n_components=5, n_restart=10, random_state=None, smooth_param=0.01,
       verbose=0),
  array([0, 0, 0, ..., 4, 3, 3], dtype=int64)],
 [TensorLDA(alpha0=0.01, converge_tol=0.0001, inference_converge_tol=1e-06,
       inference_step_size=0.001, max_inference_

In [15]:
for i in range(0,9):
    prediction = predictions[i]
    print_top_words(prediction[0], topic6_tf_feature_names, 3)

Topic #0 (prior: 0.001): CD74 SAT1 HLA-B
Topic #1 (prior: 0.004): GPM6B VIM PTN
Topic #2 (prior: 0.005): TUBB2B STMN1 GPM6A

Topic #0 (prior: 0.001): CD74 SAT1 HLA-E
Topic #1 (prior: 0.003): TUBB2B STMN1 GPM6A
Topic #2 (prior: 0.003): GPM6B VIM PTN
Topic #3 (prior: 0.004): NME1 CCT7 TUBB2B

Topic #0 (prior: 0.001): CD74 SAT1 HLA-B
Topic #1 (prior: 0.001): GPM6B GABARAPL2 S100B
Topic #2 (prior: 0.002): TUBB2B GPM6A STMN1
Topic #3 (prior: 0.002): VIM GPM6B PTPRZ1
Topic #4 (prior: 0.003): NME1 CCT7 H2AFZ

Topic #0 (prior: 0.000): GABARAPL2 GPM6B TMEM59
Topic #1 (prior: 0.001): CD74 SAT1 HLA-E
Topic #2 (prior: 0.002): PTPRZ1 GPM6B PTN
Topic #3 (prior: 0.002): DNAJB6 LDHA BZW1
Topic #4 (prior: 0.002): TUBB2B GPM6A MAP2
Topic #5 (prior: 0.003): NME1 TUBB2B NME2

Topic #0 (prior: 0.000): GABARAPL2 GPM6B TMEM59
Topic #1 (prior: 0.001): CD74 SAT1 HLA-E
Topic #2 (prior: 0.001): VIM RPL13A MYL12B
Topic #3 (prior: 0.001): CLK1 DNAJB6 SERINC1
Topic #4 (prior: 0.002): PTPRZ1 GPM6B PTN
Topic #5 (prio

IndexError: list index out of range